package:
  name: "pyintegralall"
  version: "0.0.5"

about:
  summary: https://github.com/neutrinomuon/IntegralALL
  license_file: LICENSE.txt

source:
  path: .

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - {{ compiler('fortran') }}
  run:
    - {{ compiler('fortran') }}
	
extra:
  recipe-maintainers:
    - IntegralALL

