package:
  name: "pyintegralall"
  version: "0.0.5"

about:
  summary: https://github.com/neutrinomuon/IntegralALL
  license_file: LICENSE.txt

source:
  path: .
 
requirements:
  host:
    - python
    - numpy
    - matplotlib
  build:
    - python
  run:
    - python

extra:
  recipe-maintainers:
    - IntegralALL

