{% set name = "pyintegralall" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f3fd48d78435c5634ee7f408ea5a50c3b917763227e8123b369358cb8ce96929

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy
    - pip
    - python
  run:
    - matplotlib
    - numpy
    - python

test:
  imports:
    - pyintegralall

about:
  home: "https://github.com/neutrinomuon/IntegralALL"
  license_file: 'LICENSE.txt' 
  license_url: "https://github.com/neutrinomuon/IntegralALL/LICENSE.txt"
  summary: "Integrate arrays, functions numerically using different methods in Python. Original Fortran 2003+ legacy routines date back to 2003-2004. Read the LICENSE.txt file."
  doc_url: "https://github.com/neutrinomuon/IntegralALL/"
  description: '../README.md'

extra:
  recipe-maintainers:
    - neutrinomuon
